sudo: required

language: crystal

services:
- docker

before_install:
- docker pull crystallang/crystal:latest

script:
- docker run --rm -v $(pwd):/app -w /app crystallang/crystal:latest bash -c "apt-get update -qq && apt-get install -y -qq libxml2-dev"
- docker run --rm -v $(pwd):/app -w /app crystallang/crystal:latest bash -c "crystal -v" # Print out Crystal version for debugging
- docker run --rm -v $(pwd):/app -w /app crystallang/crystal:latest bash -c "shards"
- docker run --rm -v $(pwd):/app -w /app crystallang/crystal:latest bash -c "crystal tool format --check src/"
- docker run --rm -v $(pwd):/app -w /app crystallang/crystal:latest bash -c "bin/test"
